// Copyright 2022, David Lawrence
// Subject to the terms in the LICENSE file found in the top-level directory.
//
//
// This is a placehoder that will be superceeded by a file generated by the
// make_datamodel_glue.py script. The generated file will be placed in the
// cmake build directory (e.g. build/services/io/podio/datamodel_includes.h
//
// This placeholder is needed so root's root_generate_dictionary() macro in
// cmake can find the file during the cmake phase. The actual file used will
// be generated during the build phase.
//
// The generated file will have contents that look like this following.

//#include <edm4hep/EventHeaderCollection.h>
//#include <edm4hep/MCParticleCollection.h>
//#include <edm4hep/SimTrackerHitCollection.h>
//#include <edm4hep/CaloHitContributionCollection.h>
//#include <edm4hep/SimCalorimeterHitCollection.h>
//#include <edm4hep/RawCalorimeterHitCollection.h>
//#include <edm4hep/CalorimeterHitCollection.h>
//#include <edm4hep/ParticleIDCollection.h>
//#include <edm4hep/ClusterCollection.h>
//#include <edm4hep/TrackerHitCollection.h>
//#include <edm4hep/TrackerHitPlaneCollection.h>
//#include <edm4hep/TPCHitCollection.h>
//#include <edm4hep/TrackCollection.h>
//#include <edm4hep/VertexCollection.h>
//#include <edm4hep/ReconstructedParticleCollection.h>
//#include <edm4hep/MCRecoParticleAssociationCollection.h>
//#include <edm4hep/MCRecoCaloAssociationCollection.h>
//#include <edm4hep/MCRecoTrackerAssociationCollection.h>
//#include <edm4hep/MCRecoTrackerHitPlaneAssociationCollection.h>
//#include <edm4hep/MCRecoCaloParticleAssociationCollection.h>
//#include <edm4hep/MCRecoClusterParticleAssociationCollection.h>
//#include <edm4hep/MCRecoTrackParticleAssociationCollection.h>
//#include <edm4hep/RecoParticleVertexAssociationCollection.h>
