
// This file automatically generated by the make_datamodel.py script

#include <edm4hep/EventHeaderCollection.h>
#include <edm4hep/MCParticleCollection.h>
#include <edm4hep/SimTrackerHitCollection.h>
#include <edm4hep/CaloHitContributionCollection.h>
#include <edm4hep/SimCalorimeterHitCollection.h>
#include <edm4hep/RawCalorimeterHitCollection.h>
#include <edm4hep/CalorimeterHitCollection.h>
#include <edm4hep/ParticleIDCollection.h>
#include <edm4hep/ClusterCollection.h>
#include <edm4hep/TrackerHitCollection.h>
#include <edm4hep/TrackerHitPlaneCollection.h>
#include <edm4hep/TPCHitCollection.h>
#include <edm4hep/TrackCollection.h>
#include <edm4hep/VertexCollection.h>
#include <edm4hep/ReconstructedParticleCollection.h>
#include <edm4hep/MCRecoParticleAssociationCollection.h>
#include <edm4hep/MCRecoCaloAssociationCollection.h>
#include <edm4hep/MCRecoTrackerAssociationCollection.h>
#include <edm4hep/MCRecoTrackerHitPlaneAssociationCollection.h>
#include <edm4hep/MCRecoCaloParticleAssociationCollection.h>
#include <edm4hep/MCRecoClusterParticleAssociationCollection.h>
#include <edm4hep/MCRecoTrackParticleAssociationCollection.h>
#include <edm4hep/RecoParticleVertexAssociationCollection.h>
