// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2025 Wouter Deconinck

#pragma once

#include <podio/podioVersion.h>

// Use modern implementation for podio >= 1.3
#if defined(podio_VERSION_MAJOR) && defined(podio_VERSION_MINOR)
#if (podio_VERSION_MAJOR > 1) || (podio_VERSION_MAJOR == 1 && podio_VERSION_MINOR >= 3)
#define USE_MODERN_PODIO_GLUE 1
#endif
#endif

#ifdef USE_MODERN_PODIO_GLUE
// Use modern C++ implementation with TypeLists
#include "services/io/podio/datamodel_glue.h" // IWYU pragma: export
#else
// Use legacy Python-generated implementation
// This file is generated by make_datamodel_glue.py at build time
#include "services/io/podio/datamodel_glue_legacy.h" // IWYU pragma: export
#endif
