// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2025 Wouter Deconinck

#pragma once

#include "services/io/podio/datamodel_select_compat.h"

#ifdef USE_MODERN_PODIO_GLUE
// Use modern C++ implementation with TypeLists
#include "services/io/podio/datamodel_glue.h" // IWYU pragma: export
#else
// Use legacy Python-generated implementation
// This file is generated by make_datamodel_glue.py at build time
#include "services/io/podio/datamodel_glue_legacy.h" // IWYU pragma: export
#endif
