#!/usr/bin/env python

#
#  This is a stop gap and not intended for long term.  2022-07-09  DL
#
# This will scan the list of files in the datamodel directory and
# using the filenames generate some C++ code that can be used by
# the JEventSourcePODIO to read all of those types in.
#

import os
import sys
import glob

collectionfiles = glob.glob('datamodel/*Collection.h')
header_lines = []
code_lines = []
for f in collectionfiles:
    basename = f.split('/')[1].split('Collection.h')[0]
    header = '#include "' + f + '"'
    code = '    GetPODIOData<'+basename+',  '+basename+'Collection>("'+basename+'s", event, store);'
    header_lines += [header]
    code_lines += [code]

with open('datamodel_glue.h', 'w') as f:
    f.write('\n// This file automatically generated by the make_datamodel.py script\n')
    f.write('\n'.join(header_lines))
    f.write('\nstatic void GetAllPODIOData(std::shared_ptr <JEvent> &event, podio::EventStore &store){\n')
    f.write('\n'.join(code_lines))
    f.write('\n}\n')
    f.close()
