name: doxygen

on:
  push:
  schedule:
    - cron: '41 4 * * 0'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      volumes:
      - /home/runner/work/_temp:/home/runner/work/_temp
      # FIXME hard-coded: see https://github.com/actions/upload-pages-artifact/pull/14
    steps:
    - uses: actions/checkout@v2
    - run: |
        apk add doxygen graphviz
        doxygen Doxyfile
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: html/
        if-no-files-found: error
    - run: |
        apk add tar bash
        # FIXME bash not really required: see https://github.com/actions/upload-pages-artifact/pull/14
    - uses: actions/upload-pages-artifact@v1
      if: github.ref == 'refs/heads/main'
      with:
        path: html/
        retention-days: 7

  deploy-docs:
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
