on:
  workflow_call:


jobs:
  get-docs-from-this-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Download docs artifact (this PR)
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: publishing_docs/pr/${{ github.event.pull_request.number }}
      - name: Download capybara artifact (this PR)
        uses: actions/download-artifact@v4
        with:
          name: capybara
          path: publishing_docs/pr/${{ github.event.pull_request.number }}/capybara
      - name: Remove doxygen in PR
        run: rm -rf publishing_docs/pr/${{ github.event.pull_request.number }}/doxygen
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages-staging-pr-${{ github.event.pull_request.number }}
          path: publishing_docs/
          if-no-files-found: ignore
