on:
  workflow_call:

jobs:
  get-docs-from-main:
    runs-on: ubuntu-24.04
    steps:
      # Note:
      # - If we run this on a non-main branch, we download from main with action-download-artifact.
      # - If we run this on the main branch, we have to download from this pipeline with download-artifact.
      - name: Download docs artifact (in PR)
        uses: dawidd6/action-download-artifact@v11
        if: github.ref_name != 'main'
        with:
          branch: main
          path: publishing_docs/
          name: docs
          workflow: ".github/workflows/linux-eic-shell.yml"
          workflow_conclusion: "completed"
          if_no_artifact_found: fail
      - name: Download docs artifact (on main)
        uses: actions/download-artifact@v4
        if: github.ref_name == 'main'
        with:
          name: docs
          path: publishing_docs/
      - name: Download capybara artifact (in PR)
        id: download_capybara
        uses: dawidd6/action-download-artifact@v11
        if: github.ref_name != 'main'
        with:
          commit: ${{ matrix.head_sha }}
          path: publishing_docs/capybara/
          name: capybara
          workflow: ".github/workflows/linux-eic-shell.yml"
          workflow_conclusion: "completed"
          if_no_artifact_found: ignore
      - name: Download capybara artifact (on main)
        uses: actions/download-artifact@v4
        if: github.ref_name == 'main'
        with:
          name: capybara
          path: publishing_docs/capybara/
      - name: Populate capybara summary (on main)
        if: github.ref_name == 'main' || steps.download_capybara.outputs.found_artifact == 'true'
        run: |
         echo "### Capybara summary for main" >> publishing_docs/capybara/index.md
         find publishing_docs/capybara/ -mindepth 1 -maxdepth 1 -type d -printf \
           "- [%f](https://eicrecon.epic-eic.org/capybara/%f/index.html)\n" | sort >> publishing_docs/capybara/index.md
      - name: Create capybara step summary (this PR)
        if: github.ref_name == 'main'
        run: |
          cat publishing_docs/capybara/index.md >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages-staging-main
          path: publishing_docs/
          if-no-files-found: error
